# Generated by Django 5.0.6 on 2024-06-12 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelfaqs_hotelfeatures_hotelgallery_roomtype_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Initiated', 'Initiated'), ('Failed', 'Failed'), ('Refunding', 'Refunding'), ('Refunded', 'Refunded'), ('Unpaid', 'Unpaid'), ('Expired', 'Expired')], max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
