# Generated by Django 5.0.6 on 2024-06-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
